name = "b2"

workers_dev = true
compatibility_date = "2023-09-04"

main = "index.js"

routes = [
    { pattern = "s3.vaayne.com", custom_domain = true },
    { pattern = "s3.recally.io", custom_domain = true },
    { pattern = "s3.tokenflux.ai", custom_domain = true },
]

[vars]
B2_APPLICATION_KEY_ID = "004aba9b1677b870000000006" # CloudflareWorkerReader Key
B2_ENDPOINT = "s3.us-west-004.backblazeb2.com"
BUCKET_NAME = "$path"
ALLOW_LIST_BUCKET = "false"
RCLONE_DOWNLOAD = "true"
